load heart_scale.mat
model                                  ...
    = svmtrain_libsvm(  heart_scale_label, ...
    heart_scale_inst, '-s 0 -g 0.07 -c 1');
[predict_label, accuracy, dec_values]   ...
    = svmpredict_libsvm(heart_scale_label, heart_scale_inst, model); % test the training data

support_vectors                        ...
    = full(model.SVs); 
support_vector_class                   ...
    = sign(model.sv_coef);